/* Q. 389
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

var findTheDifference = function(s, t) {
  let sumS = 0, sumT = 0;

  for (let char of s) {
    sumS += char.charCodeAt(0);
  }

  for (let char of t) {
    sumT += char.charCodeAt(0);
  }

  return String.fromCharCode(sumT - sumS);    
    
};